### ISSUE TITLE
Word Read/Write in I2cDeviceClient?

### ISSUE THREAD

**Issue by luciengaitskell** [SwerveRobotics/ftc_app#56]
Is there any capability for word read and writes in the I2cDeviceClient class. If not, is there any planned?

**Comment by rgatkinson** [comment]
We’ve thought about this, off and on, but have yet to be compelled ☺. Do you happen to have a motivating example?

**Comment by luciengaitskell** [comment]
I have a MaxSonar Ultrasound sensor with requires a word read. Also, I have a led which changes color using three bytes. Is there any way to work with these with the current library?

**Comment by rgatkinson** [comment]
Sure. The easiest way is to read the bytes as a byte array, then use a ByteBuffer (I think it’s called; I’m away from my main machine at the moment) to convert that to an integer, either little endian, or big endian, as appropriate.

**Comment by luciengaitskell** [comment]
Another question, what do I put in for the "OpMode context" in the "ClassFactory.createI2cDeviceClient()"?

**Comment by rgatkinson** [comment]
Just pass the instance of the (subclass of) OpMode that you are running.

**Comment by luciengaitskell** [comment]
Ok. Why is it needed?

**Comment by luciengaitskell** [comment]
I'm trying to use multiple sensors on the same port using your I2cDeviceClient library, yet I seems to hang the OpMode when I try to use it

**Comment by rgatkinson** [comment]
Using multiple sensors on one port is not something that is supported. Is that important to you? Can you help us understand by illustrating with an example?
