### ISSUE TITLE
Latest update says Incompatible apps

### ISSUE THREAD

**Issue by crowcasso** [SwerveRobotics/ftc_app#62]
After updating to the latest version of Swerve, our robot controller now reports "Incompatible apps: v1 and v2". In Settings --> Library Version it now reports "developer_build" instead of 11.15.04. Are these related?

**Comment by cmacfarl** [comment]
You need to side load the DS.  It's in docs/app/....

Craig

**Comment by crowcasso** [comment]
Thanks!

**Comment by higgs241** [comment]
Do we have to worry about event people side loading fresh versions from FIRST that are incompatible with the swerve app at events?

**Comment by crowcasso** [comment]
This should not happen.  The software inspectors should be okay with swerve software as long as your setup works properly. The software inspectors look for Android version, name of phones, if there is a direct wifi connection, airport more, etc. They do not look directly at the software. 

-joel



On February 5, 2016 at 6:47:06 PM, higgs241 (notifications@github.com) wrote:

Do we have to worry about event people side loading fresh versions from FIRST that are incompatible with the swerve app at events?
