### ISSUE TITLE
ColorSensor issues with 1.5.2

### ISSUE THREAD

**Issue by crowcasso** [SwerveRobotics/ftc_app#67]
Using the modern robotics color sensor causes the following error now:

ClassCastException - com.qualcomm.hardware.modernrobotics.ModernRoboticsI2cColorSensor cannot be cast to com.qualcomm.robotcore.hardware.Engagable.

The code was good before updating today. 

Any ideas?  Thanks!

**Comment by Ace314159** [comment]
I also have gotten this error.

**Comment by crowcasso** [comment]
Looks like we might be missing:  com.qualcomm.robotcore.hardware.usb.RobotUsbModule

This gives me an error in II2cDeviceClient.java  (which also extends Engagable).

**Comment by rgatkinson** [comment]
I'll look into this; 'pologies for the inconvenience.

**Comment by Ace314159** [comment]
Does the commit 2b8e462d5d195f5b286233377457bc42f3cd1ecd fix this bug?

**Comment by rgatkinson** [comment]
It should, yes.

**Comment by crowcasso** [comment]
I am no longer having the issue after the fix mentioned above. 

Thanks for the response and make this code available to us.
