### ISSUE TITLE
Allow access to ModernRoboticsI2CGyro from SynchronousOpMode

### ISSUE THREAD

**Issue by NoahAndrews** [SwerveRobotics/ftc_app#76]
The ModernRoboticsI2CGyro class has some methods that the GyroSensor interface doesn't expose, like `getIntegratedZValue()`. Is there a way to gain access to them from a SynchronousOpMode? `ModernRoboticsI2cGyro gyro = (ModernRoboticsI2cGyro)hardwareMap.gyroSensor.get("gyro");` results in a ClassCastException, saying that ThunkedGyroSensor cannot be cast to MondernRoboticsI2CGyro.

**Comment by Ace314159** [comment]
Use `unthunkedhardwaremap`.

**Comment by NoahAndrews** [comment]
Awesome, thanks!
