### ISSUE TITLE
I2c Reading Returns -1

### ISSUE THREAD

**Issue by luciengaitskell** [SwerveRobotics/ftc_app#84]
I have tried to read two different (_Blink M LED_ and _Lidar-Lite v2_) sensors using this basic code (I have been able to read and write from them using SMBus on a raspberry pi):
```
II2cDeviceClient sensor = ClassFactory.createI2cDeviceClient(this, ClassFactory.createI2cDevice(hardwareMap.i2cDevice.get("sensor")), i2cAddress, false);
sensor.engage();
Log.d("readValue", "Version Number: " + String.valueOf(ls.read8(readAddress)));
sensor.disengage();
sensor.close();
```

Yet in the log it prints:
> Address:-1

Writing does work. I have tried different memory addresses and nothing seems to be working.

**Comment by rgatkinson** [comment]
What value(s) are you passing for the i2cAddress parameter?

**Comment by rgatkinson** [comment]
In the FTC SDK you need to take the address on the datasheet / whatever you used in Arduino or Rasberry Pi and multiply it by two.

**Comment by rgatkinson** [comment]
Example: the BlinkM data sheet lists its address as 0x09. So you should pass 0x12.

**Comment by luciengaitskell** [comment]
I was passing `0x00` (general address) to `i2cAddress` as `0x09` wasn't working. Thank you for telling me that. It was successfully writing but not reading.

**Comment by rgatkinson** [comment]
You're welcome. I agree that it is confusing.

**Comment by luciengaitskell** [comment]
Do you know how to fix the reading error though?

**Comment by cmacfarl** [comment]
I happen to know the guy who developed the BlinkM and passed this on to him as a fun, "Hey look your device is being used in FTC" sort of thing and he responded that, yes, indeed reads don't work through the broadcast address, which when you think about it makes a certain amount of sense.  If you have N devices on the bus which one is going to respond with your data?
